

# Nombre de la aplicaci�n
spring.application.name=identipat-ia

# Puerto del servidor
server.port=8082

# Context path (ajusta si quieres exponer la app bajo un prefijo)
server.servlet.context-path=/identipat-ia/

spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:h2:mem:identipatdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Carpeta con los archivos estaticos del frontend (Angular) compilado
spring.web.resources.static-locations=file:frontend/dist/browser/

#formato de fecha y hora
spring.jackson.date-format=dd/MM/yyyy HH:mm:ss
spring.jackson.time-zone=America/Lima

# Tambien puedes configurar la zona horaria del sistema Java (opcional, pero recomendable)
spring.application.time-zone=America/Lima