CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255),
    first_name VARCHAR(255),
    paternal_last_name VARCHAR(255),
    maternal_last_name VARCHAR(255),
    doi VARCHAR(255) NOT NULL,
    doi_type VARCHAR(255),
    birth_date DATE,
    gender VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    mobile_phone VARCHAR(255),
    user_type VARCHAR(255),
    profession VARCHAR(255),
    status VARCHAR(1) NOT NULL,
    creation_date TIMESTAMP(6),
    CONSTRAINT uk_users_doi UNIQUE (doi)
);
