spring:
  application:
    name: identipat-ia
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: ${APP_TIME_ZONE:America/Lima}
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: ${APP_TIME_ZONE:America/Lima}
  web:
    resources:
      static-locations: file:./frontend/dist/identipat-ia/browser/

server:
  servlet:
    context-path: /identipat-ia

app:
  jwt:
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
